/**
 * Shell 补全脚本生成器
 * 
 * 为各种 shell 生成命令补全脚本
 * 
 * @example
 * ```ts
 * const completion = new CompletionManager()
 * const script = completion.generate('zsh')
 * ```
 */
export class CompletionManager {
  private commandName: string
  private commands: CommandDefinition[]

  constructor(commandName = 'lgit') {
    this.commandName = commandName
    this.commands = this.getCommandDefinitions()
  }

  /**
   * 生成补全脚本
   */
  generate(shell: 'bash' | 'zsh' | 'fish' | 'powershell'): string {
    switch (shell) {
      case 'bash':
        return this.generateBash()
      case 'zsh':
        return this.generateZsh()
      case 'fish':
        return this.generateFish()
      case 'powershell':
        return this.generatePowerShell()
      default:
        throw new Error(`不支持的 shell: ${shell}`)
    }
  }

  /**
   * 获取安装说明
   */
  getInstallInstructions(shell: 'bash' | 'zsh' | 'fish' | 'powershell'): string {
    const cmd = this.commandName

    switch (shell) {
      case 'bash':
        return `# 添加到 ~/.bashrc 或 ~/.bash_profile
${cmd} completion bash >> ~/.bashrc
source ~/.bashrc

# 或者保存到单独文件
${cmd} completion bash > /etc/bash_completion.d/${cmd}`

      case 'zsh':
        return `# 添加到 ~/.zshrc
${cmd} completion zsh >> ~/.zshrc
source ~/.zshrc

# 或者添加到 fpath
${cmd} completion zsh > ~/.zsh/completions/_${cmd}
# 确保 ~/.zsh/completions 在 fpath 中`

      case 'fish':
        return `# 保存到 fish 补全目录
${cmd} completion fish > ~/.config/fish/completions/${cmd}.fish`

      case 'powershell':
        return `# 添加到 PowerShell 配置文件
${cmd} completion powershell >> $PROFILE
. $PROFILE

# 或者在当前会话中直接使用
${cmd} completion powershell | Out-String | Invoke-Expression`

      default:
        return ''
    }
  }

  /**
   * 生成 Bash 补全脚本
   */
  private generateBash(): string {
    const cmd = this.commandName
    const commands = this.commands.map(c => c.name).join(' ')
    
    let script = `# ${cmd} bash completion script
# Generated by @ldesign/git-cli

_${cmd}_completions() {
    local cur prev words cword
    _init_completion || return

    local commands="${commands}"

    if [[ \${cword} -eq 1 ]]; then
        COMPREPLY=($(compgen -W "\${commands}" -- "\${cur}"))
        return
    fi

    local command=\${words[1]}

    case "\${command}" in
`

    for (const cmd of this.commands) {
      if (cmd.subcommands && cmd.subcommands.length > 0) {
        const subs = cmd.subcommands.join(' ')
        script += `        ${cmd.name})
            if [[ \${cword} -eq 2 ]]; then
                COMPREPLY=($(compgen -W "${subs}" -- "\${cur}"))
            fi
            ;;
`
      }
    }

    script += `        *)
            COMPREPLY=()
            ;;
    esac
}

complete -F _${cmd}_completions ${cmd}
complete -F _${cmd}_completions ldesign-git
`

    return script
  }

  /**
   * 生成 Zsh 补全脚本
   */
  private generateZsh(): string {
    const cmd = this.commandName
    
    let script = `#compdef ${cmd} ldesign-git
# ${cmd} zsh completion script
# Generated by @ldesign/git-cli

_${cmd}() {
    local -a commands
    commands=(
`

    for (const c of this.commands) {
      script += `        '${c.name}:${c.description}'\n`
    }

    script += `    )

    _arguments -C \\
        '1: :->command' \\
        '*: :->args'

    case \$state in
        command)
            _describe -t commands 'command' commands
            ;;
        args)
            case \$words[2] in
`

    for (const c of this.commands) {
      if (c.subcommands && c.subcommands.length > 0) {
        script += `                ${c.name})
                    local -a subcommands
                    subcommands=(
`
        for (const sub of c.subcommands) {
          script += `                        '${sub}'\n`
        }
        script += `                    )
                    _describe -t subcommands 'subcommand' subcommands
                    ;;
`
      }
    }

    script += `            esac
            ;;
    esac
}

_${cmd} "\$@"
`

    return script
  }

  /**
   * 生成 Fish 补全脚本
   */
  private generateFish(): string {
    const cmd = this.commandName
    
    let script = `# ${cmd} fish completion script
# Generated by @ldesign/git-cli

# Disable file completion by default
complete -c ${cmd} -f
complete -c ldesign-git -f

# Main commands
`

    for (const c of this.commands) {
      script += `complete -c ${cmd} -n "__fish_use_subcommand" -a "${c.name}" -d "${c.description}"\n`
      script += `complete -c ldesign-git -n "__fish_use_subcommand" -a "${c.name}" -d "${c.description}"\n`
    }

    script += `\n# Subcommands\n`

    for (const c of this.commands) {
      if (c.subcommands && c.subcommands.length > 0) {
        for (const sub of c.subcommands) {
          script += `complete -c ${cmd} -n "__fish_seen_subcommand_from ${c.name}" -a "${sub}"\n`
          script += `complete -c ldesign-git -n "__fish_seen_subcommand_from ${c.name}" -a "${sub}"\n`
        }
      }
    }

    return script
  }

  /**
   * 生成 PowerShell 补全脚本
   */
  private generatePowerShell(): string {
    const cmd = this.commandName
    
    let script = `# ${cmd} PowerShell completion script
# Generated by @ldesign/git-cli

$script:${cmd}Commands = @{
`

    for (const c of this.commands) {
      if (c.subcommands && c.subcommands.length > 0) {
        script += `    '${c.name}' = @('${c.subcommands.join("', '")}')\n`
      } else {
        script += `    '${c.name}' = @()\n`
      }
    }

    script += `}

Register-ArgumentCompleter -CommandName ${cmd},ldesign-git -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $commands = $commandAst.CommandElements
    
    if ($commands.Count -eq 1) {
        # Complete main commands
        $script:${cmd}Commands.Keys | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
    }
    elseif ($commands.Count -eq 2) {
        # Complete subcommands
        $mainCommand = $commands[1].Extent.Text
        if ($script:${cmd}Commands.ContainsKey($mainCommand)) {
            $script:${cmd}Commands[$mainCommand] | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
            }
        }
    }
}
`

    return script
  }

  /**
   * 获取命令定义
   */
  private getCommandDefinitions(): CommandDefinition[] {
    return [
      { name: 'status', description: '查看 Git 状态', alias: 'st' },
      { name: 'init', description: '初始化 Git 仓库' },
      { name: 'clone', description: '克隆远程仓库' },
      { name: 'pull', description: '拉取远程更新' },
      { name: 'push', description: '推送到远程仓库' },
      { name: 'checkout', description: '切换分支或恢复文件', alias: 'co' },
      { name: 'merge', description: '合并分支' },
      { name: 'add', description: '添加文件到暂存区' },
      { name: 'reset', description: '重置当前 HEAD' },
      { name: 'fetch', description: '获取远程更新' },
      { 
        name: 'branch', 
        description: '分支管理', 
        alias: 'br',
        subcommands: ['list', 'create', 'delete', 'rename', 'switch', 'current', 'merged', 'cleanup']
      },
      { 
        name: 'tag', 
        description: '标签管理',
        subcommands: ['list', 'create', 'delete', 'show', 'push']
      },
      { 
        name: 'commit', 
        description: '智能提交命令',
        subcommands: ['smart', 'validate', 'analyze']
      },
      { 
        name: 'remote', 
        description: '远程仓库管理',
        subcommands: ['list', 'add', 'remove', 'rename', 'url', 'prune']
      },
      { 
        name: 'stash', 
        description: '暂存管理',
        subcommands: ['list', 'save', 'pop', 'apply', 'drop', 'clear', 'show']
      },
      { 
        name: 'diff', 
        description: '查看差异',
        subcommands: ['show', 'staged', 'file', 'commit', 'branches', 'stat']
      },
      { 
        name: 'log', 
        description: '查看日志',
        subcommands: ['show', 'oneline', 'graph', 'file', 'search', 'author', 'since']
      },
      { 
        name: 'config', 
        description: '配置管理',
        subcommands: ['list', 'get', 'set', 'unset', 'edit', 'user', 'editor']
      },
      { 
        name: 'rebase', 
        description: '变基操作',
        subcommands: ['interactive', 'onto', 'continue', 'abort', 'skip']
      },
      { 
        name: 'workflow', 
        description: '工作流管理',
        subcommands: ['init', 'feature', 'release', 'hotfix', 'finish']
      },
      { 
        name: 'analyze', 
        description: '仓库分析',
        subcommands: ['commits', 'contributors', 'files', 'timeline']
      },
      { name: 'report', description: '生成报告' },
      { 
        name: 'conflict', 
        description: '冲突管理',
        subcommands: ['list', 'show', 'resolve', 'theirs', 'ours']
      },
      { 
        name: 'hooks', 
        description: 'Git Hooks 管理',
        subcommands: ['list', 'add', 'remove', 'enable', 'disable', 'run']
      },
      { 
        name: 'submodule', 
        description: '子模块管理',
        alias: 'sm',
        subcommands: ['list', 'add', 'init', 'update', 'remove', 'sync', 'pull', 'summary', 'status', 'foreach', 'set-branch', 'clone']
      },
      { name: 'ui', description: '启动 Web UI' },
      { 
        name: 'lfs', 
        description: 'Git LFS 管理',
        subcommands: ['install', 'track', 'untrack', 'status', 'pull', 'push', 'prune']
      },
      { 
        name: 'worktree', 
        description: '工作树管理',
        subcommands: ['list', 'add', 'remove', 'prune', 'lock', 'unlock']
      },
      { 
        name: 'monorepo', 
        description: 'Monorepo 管理',
        subcommands: ['packages', 'changed', 'run', 'version']
      },
      { 
        name: 'bisect', 
        description: '二分查找',
        subcommands: ['start', 'good', 'bad', 'reset', 'run', 'log']
      },
      { 
        name: 'blame', 
        description: '代码追溯',
        subcommands: ['show', 'line', 'summary']
      },
      { 
        name: 'reflog', 
        description: 'Reflog 管理',
        subcommands: ['show', 'expire', 'delete']
      },
      { 
        name: 'notes', 
        description: 'Git Notes 管理',
        subcommands: ['list', 'add', 'show', 'edit', 'remove', 'copy']
      },
      // 新增命令
      { 
        name: 'doctor', 
        description: 'Git 健康检查',
        subcommands: ['check', 'fix']
      },
      { 
        name: 'undo', 
        description: '智能撤销向导',
        subcommands: ['unstage', 'discard', 'commit', 'amend', 'merge', 'rebase']
      },
      { 
        name: 'alias', 
        description: '别名管理',
        subcommands: ['list', 'add', 'remove', 'template']
      },
      { 
        name: 'cherry-pick', 
        description: 'Cherry-pick 操作',
        alias: 'cp',
        subcommands: ['pick', 'continue', 'abort', 'skip']
      },
      { 
        name: 'archive', 
        description: '创建归档',
        subcommands: ['create', 'list', 'preview']
      },
      { 
        name: 'patch', 
        description: '补丁管理',
        subcommands: ['create', 'apply', 'check', 'list']
      },
      { 
        name: 'backup', 
        description: '备份管理',
        subcommands: ['create', 'restore', 'list', 'cleanup']
      },
      { 
        name: 'scan', 
        description: '安全扫描',
        subcommands: ['secrets', 'large-files', 'duplicates', 'full']
      },
      { 
        name: 'credential', 
        description: '凭证管理',
        subcommands: ['helper', 'store', 'list', 'clear']
      },
      { 
        name: 'completion', 
        description: '生成补全脚本',
        subcommands: ['bash', 'zsh', 'fish', 'powershell']
      },
      { 
        name: 'cleanup', 
        description: '清理工具',
        subcommands: ['branches', 'remote', 'cache', 'all']
      },
      { 
        name: 'stats', 
        description: '统计信息',
        subcommands: ['summary', 'author', 'timeline', 'files', 'activity']
      }
    ]
  }

  /**
   * 获取支持的 shell 列表
   */
  getSupportedShells(): string[] {
    return ['bash', 'zsh', 'fish', 'powershell']
  }
}

interface CommandDefinition {
  name: string
  description: string
  alias?: string
  subcommands?: string[]
}
